### ISSUE TITLE
ResourceLoader uses wrong 'user-skins' path for resources from 'canasta-skins' directory

### ISSUE THREAD

**Issue by pastakhov** [CanastaWiki/Canasta#68] opened 2022-04-08 14:44 UTC
Most likely we can face similar issues for extensions from canasta-extensions directory.
I don't think we can easily fix it in mw core, the issue is related Canasta design.
cfLoadSkin() function changes $wgStyleDirectory and $wgStylePath variables, calls wfLoadSkin() function and restores values of the variables.  It allows to load skins from canasta-skins directory, but when ResourceLoader compiles (for example) less files, it seems it uses original values of the variables.

For example `.background-image-svg( 'images/external-link-ltr-icon.svg' );` line in `w/canasta-skins/Vector/resources/skins.vector.styles/common/typography.less` file tries to load file from `user-skins /...` directory.

We can bypass this adding a rewrite rule to Apache to look for a file in canasta-skins directory if it does not exist in user-skins directory. This approach is not very good, but should work

P.S.
`cfLoadExtension( 'Bootstrap' );` throws the error:
```
[ec247b7af6bd517a8195dde0] /wiki/Main_Page RuntimeException from line 142 of /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Hooks/SetupAfterCache.php: Expected an accessible /var/www/mediawiki/w/user-extensions/Bootstrap/resources/bootstrap path

Backtrace:

#0 /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Hooks/SetupAfterCache.php(73): Bootstrap\Hooks\SetupAfterCache->isReadablePath()
#1 /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Bootstrap.php(62): Bootstrap\Hooks\SetupAfterCache->process()
#2 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(329): Bootstrap\Bootstrap::Bootstrap\{closure}()
#3 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 /var/www/mediawiki/w/includes/HookContainer/HookRunner.php(3417): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/mediawiki/w/includes/Setup.php(694): MediaWiki\HookContainer\HookRunner->onSetupAfterCache()
#6 /var/www/mediawiki/w/includes/WebStart.php(89): require_once(string)
#7 /var/www/mediawiki/w/index.php(44): require(string)
#8 {main}
```

**Comment by tosfos** [comment] 2022-04-08 15:21
We should try passing a path as the second parameter to wfLoad*

**Comment by pastakhov** [comment] 2022-04-08 19:28
It will not help
```
function wfLoadExtension( $ext, $path = null ) {
	if ( !$path ) {
		global $wgExtensionDirectory;
		$path = "$wgExtensionDirectory/$ext/extension.json";
	}
	ExtensionRegistry::getInstance()->queue( $path );
}
```
and 
```
function cfLoadExtension( $extName ) {
	global $wgExtensionDirectory, $wgExtensionAssetsPath, $IP, $wgScriptPath;

	$realExtDirectory = $wgExtensionDirectory;
	$realExtAssetsPath = $wgExtensionAssetsPath;
	$wgExtensionDirectory = $IP . '/canasta-extensions';
	$wgExtensionAssetsPath = $wgScriptPath . '/canasta-extensions';
	wfLoadExtension( $extName );
	$wgExtensionDirectory = $realExtDirectory;
	$wgExtensionAssetsPath = $realExtAssetsPath;
}
```

**Comment by jeffw16** [comment] 2022-04-08 21:11
For the bootstrap error, see #58

**Comment by yaronkoren** [comment] 2022-04-10 15:40
Is this problem visible when using Vector (or any other skin)? Are there missing images or something?

**Comment by jeffw16** [comment] 2022-04-10 15:53
@yaronkoren Yes, in the attached image, the user icon next to the username is missing, as well as the external link icon beside the "User's Guide" link.

![image](https://user-images.githubusercontent.com/11380894/162628030-ffcf9821-49f7-40b3-acef-da4762a1eaaa.png)

**Comment by yaronkoren** [comment] 2022-04-10 16:06
Oh, that missing user icon. That was a problem before, but then this patch from February fixed it, I believe:

https://github.com/CanastaWiki/Canasta/pull/34/files

But now I see that the custom skins and extensions directories were changed from /skins and /extensions to /user-skins and /user-extensions, respectively, in this patch from about a week ago:

https://github.com/CanastaWiki/Canasta/commit/7cc8b1a045f5ee5ce0c687d62cd44535dad3b2fe

Why was this change done? And could this be the cause of the problem?

**Comment by jeffw16** [comment] 2022-04-10 16:21
This change was made as part of aligning with the specs on the spec sheet from October 2021. Perhaps 7cc8b1a introduced a regression, but on a similar vein, I'm not sure how #34 works. It sets the default paths to `/skins/` and `/extensions/`, but this wouldn't be applicable to the `cfLoadExtension` call.

I think the easy way to fix this is to drop `cfLoadExtension` altogether, per feedback from EMWCon and other technical considerations. It is soon becoming untenable with the upcoming YAML-based configuration changes. It should be easier for us to detect whether a user-installed extension exists before attempting to load the bundled extension. I think it is reasonable and intuitive for user-installed extensions to always override bundled extensions. In case there are two versions and the user wanted to use the bundled extension, they can move their own extension version out of their `extensions/` (known to Canasta as `user-extensions/`) directory or rename it to something else.

**Comment by yaronkoren** [comment] 2022-04-10 17:37
You bring up a number of larger points here. It certainly seems to make sense to switch to a YAML-based approach once MediaWiki enables it - which could be as soon as the 1.39 version. However, I think that's a separate question from whether detection of extensions and skins is done. As far as I can tell, either syntax (LocalSettings or YAML) could support either approach (explicitly-stated location or detected location).

Yeah, it does seem strange that a solution involving "skins/" would fix calls to cfLoadSkin() - but I do believe this patch (#34) fixed that exact problem. If I recall correctly, it was because cfLoadSkin() added "../canasta-skins" on to the values for $wgStyleDirectory and $wgStylePath - so if these paths were not being set correctly in the first place, then cfLoadSkin()'s modifications would not work either. Anyway, the important thing is that, a month or so ago, I'm pretty sure that the loading of all skins worked, and now it (once again) doesn't.

I'm still wondering about that patch from a week ago. I don't know what's in the October 2021 document, but didn't we finalize that, as far as the wiki is concerned, custom extensions and skins are located at "extensions/" and "skins/"?

**Comment by jeffw16** [comment] 2022-04-13 15:28
@yaronkoren and I have decided that we should change from `user-skins/` and `user-extensions/` back to `skins/` and `extensions/` so that we can get rid of this issue.

**Comment by yaronkoren** [comment] 2022-04-13 15:57
What's an example of a bundled extension or skin that would need patching, besides Bootstrap?

**Comment by pastakhov** [comment] 2022-04-13 16:52
We faced this issue in Bootstrap and Vector skin, I can't say have other extensions/skins this issue. I hope they don't, but all of them which uses ResourceLoader can have it. For me personally, one such issue is enough to start looking for another solution that will work in all cases, especially if this image is positioned as suitable for other as a base.
It is my opinion...

**Comment by yaronkoren** [comment] 2022-04-13 17:59
We've discussed this kind of thing before, but I really feel that, if it's just a few extensions and/or skins that have problems, we should just modify or (in the case of Bootstrap) locally patch them. If it's more than just a few, then it might be worth looking for another solution, but as it is I think the current overall approach is fine.

**Comment by tosfos** [comment] 2022-04-26 18:48
Can this (and the related PR) be closed now? https://github.com/CanastaWiki/Canasta/pull/83 was merged

**Comment by tosfos** [comment] 2022-04-27 13:56
It looks like #83 still requires some follow-up as it left a bunch of references in the code to "canasta-extensions".

**Closed** 2022-04-29 12:13 UTC
